-- Configuração de tabelas
-- Tabela para armazenar os bares
CREATE TABLE bars (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  name TEXT NOT NULL,
  location TEXT NOT NULL,
  maps_url TEXT,
  description TEXT NOT NULL,
  rating NUMERIC(3,1) NOT NULL CHECK (rating >= 0 AND rating <= 5),
  image TEXT NOT NULL,
  additional_images TEXT[] DEFAULT '{}'::text[],
  tags TEXT[] NOT NULL,
  events JSONB NOT NULL DEFAULT '[]'::jsonb,
  phone TEXT,
  instagram TEXT,
  facebook TEXT,
  hours TEXT
);

-- Tabela para armazenar os eventos
CREATE TABLE events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  title TEXT NOT NULL,
  date TEXT NOT NULL,
  time TEXT NOT NULL,
  location TEXT NOT NULL,
  description TEXT NOT NULL,
  image TEXT NOT NULL
);

-- Configuração de buckets de storage
-- Primeiro, remova buckets e políticas existentes se houver
DROP POLICY IF EXISTS "Imagens de bares são públicas" ON storage.objects;
DROP POLICY IF EXISTS "Imagens de eventos são públicas" ON storage.objects;
DROP POLICY IF EXISTS "Qualquer pessoa pode fazer upload de imagens de bares" ON storage.objects;
DROP POLICY IF EXISTS "Qualquer pessoa pode fazer upload de imagens de eventos" ON storage.objects;
DROP POLICY IF EXISTS "Qualquer pessoa pode atualizar imagens" ON storage.objects;
DROP POLICY IF EXISTS "Qualquer pessoa pode excluir imagens" ON storage.objects;

-- Delete buckets if they exist, to recreate them
DELETE FROM storage.buckets WHERE id IN ('bar-images', 'event-images');

-- Crie os buckets com configurações adequadas
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES 
  ('bar-images', 'Imagens de Bares', true, 5242880, ARRAY['image/jpeg', 'image/png', 'image/gif', 'image/webp']),
  ('event-images', 'Imagens de Eventos', true, 5242880, ARRAY['image/jpeg', 'image/png', 'image/gif', 'image/webp']);

-- Políticas para o Storage
-- Permitir acesso público para leitura
CREATE POLICY "Imagens de bares são públicas" ON storage.objects
  FOR SELECT USING (bucket_id = 'bar-images');

CREATE POLICY "Imagens de eventos são públicas" ON storage.objects
  FOR SELECT USING (bucket_id = 'event-images');

-- Permitir upload de imagens para qualquer pessoa (sem autenticação)
CREATE POLICY "Qualquer pessoa pode fazer upload de imagens de bares" ON storage.objects
  FOR INSERT WITH CHECK (bucket_id = 'bar-images');

CREATE POLICY "Qualquer pessoa pode fazer upload de imagens de eventos" ON storage.objects
  FOR INSERT WITH CHECK (bucket_id = 'event-images');

-- Permitir atualização e exclusão de objetos a qualquer pessoa
CREATE POLICY "Qualquer pessoa pode atualizar imagens" ON storage.objects
  FOR UPDATE USING (true);

CREATE POLICY "Qualquer pessoa pode excluir imagens" ON storage.objects
  FOR DELETE USING (true);

-- Política de acesso para a tabela bars (acesso público completo)
CREATE POLICY "Acesso público para leitura de bares" ON bars
  FOR SELECT USING (true);

CREATE POLICY "Qualquer pessoa pode inserir bares" ON bars
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Qualquer pessoa pode atualizar bares" ON bars
  FOR UPDATE USING (true);

CREATE POLICY "Qualquer pessoa pode excluir bares" ON bars
  FOR DELETE USING (true);

-- Política de acesso para a tabela events (acesso público completo)
CREATE POLICY "Acesso público para leitura de eventos" ON events
  FOR SELECT USING (true);

CREATE POLICY "Qualquer pessoa pode inserir eventos" ON events
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Qualquer pessoa pode atualizar eventos" ON events
  FOR UPDATE USING (true);

CREATE POLICY "Qualquer pessoa pode excluir eventos" ON events
  FOR DELETE USING (true);

-- Habilitar RLS (Row Level Security) nas tabelas
ALTER TABLE bars ENABLE ROW LEVEL SECURITY;
ALTER TABLE events ENABLE ROW LEVEL SECURITY;

-- Dados de exemplo para bares
INSERT INTO bars (name, location, description, rating, image, tags, events, phone, instagram, facebook, hours) VALUES
(
  'Boteco do Blues',
  'Centro, Rua Augusta, 123',
  'Um bar aconchegante com música ao vivo todas as noites e a melhor seleção de cervejas artesanais da cidade.',
  4.8,
  'https://images.unsplash.com/photo-1514933651103-005eec06c04b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80',
  ARRAY['Música ao Vivo', 'Cerveja Artesanal', 'Petiscos'],
  '[
    {"name": "Noite de Blues & Jazz", "date": "Sexta, 20:00"},
    {"name": "Open Mic Night", "date": "Sábado, 21:00"}
  ]'::jsonb,
  '+55 11 1234-5678',
  '@botecodoblues',
  'https://www.facebook.com/botecodoblues',
  'Segunda a Quinta: 18:00 - 00:00
Sexta e Sábado: 18:00 - 02:00
Domingo: 16:00 - 22:00'
),
(
  'Rooftop Lounge',
  'Pinheiros, Av. Faria Lima, 500',
  'Bar com vista panorâmica da cidade, coquetéis exclusivos e um ambiente sofisticado para aproveitar o pôr do sol.',
  4.5,
  'https://images.unsplash.com/photo-1517457373958-b7bdd4587205?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1769&q=80',
  ARRAY['Rooftop', 'Coquetéis', 'Pôr do Sol'],
  '[
    {"name": "Sunset DJ Session", "date": "Quinta, 18:00"},
    {"name": "Cocktail Masterclass", "date": "Domingo, 16:00"}
  ]'::jsonb,
  '+55 11 1234-5678',
  '@rooftop_lounge',
  'https://www.facebook.com/rooftoplounge',
  'Terça a Quinta: 17:00 - 00:00
Sexta e Sábado: 17:00 - 03:00
Domingo: 16:00 - 22:00'
);

-- Dados de exemplo para eventos
INSERT INTO events (title, date, time, location, description, image) VALUES
(
  'Festival de Cervejas Artesanais',
  '27-28 Abril, 2025',
  '12:00 - 22:00',
  'Parque Villa-Lobos',
  'O maior festival de cervejas artesanais da cidade com mais de 50 cervejarias, food trucks e shows ao vivo.',
  'https://images.unsplash.com/photo-1513309914637-65c20a5962e1?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1770&q=80'
),
(
  'Noite de Coquetelaria',
  '15 Abril, 2025',
  '19:00 - 23:00',
  'Rooftop Lounge',
  'Aprenda a fazer coquetéis clássicos e modernos com os melhores bartenders da cidade.',
  'https://images.unsplash.com/photo-1551024709-8f23befc6f87?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1770&q=80'
); 